---
title: "Online Retail Store Analysis"
author: "Olamide Adu"
date: "2023-08-07"
output:
   html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    dev: svg
    theme: simplex
    highlight: zenburn
    code_folding: show
    df_print: paged
---

# Online Retail Store Analysis

# Description
The dashboard is an example of an online store focusing on it's products performance. The dashboard shows the sales performance, gave an insights on customers behavior and showed how the stored performed in different countries.

## Goal
The purpose of the dashboard is to provide high-level KPI's and results at a glance.

## Project Duration
The development of this dashboard took 3 weeks. A typical dashboard takes 2 weeks to 2 months to create.

## The Data

-   InvoiceNO: invoice code for purchase made

-   StockCode: the code of the object purchased when in stock

-   Description: the description of item purchased

-   Quantity: the amount of the product purchased

-   InvoiceDate: the year,month, date, hour, minute and seconds of item purchase

-   Unitprice: the cost for one of the product

-   CustomerID: a number representing and tagging a particular customer

-   Country: the country where purchase was made.

```{r results='asis'}
cat('<iframe title="Olamide_Online_Retail" width="600" height="373.5" src="https://app.powerbi.com/view?r=eyJrIjoiZWVlZDUxYzgtNTcwMC00MDEyLWExMTUtM2E2YWIwZDEwMzRmIiwidCI6ImEzYjVmMDcxLTBlNDktNDdhMC1hNDBlLTliN2M5YzRkNjQ3ZSIsImMiOjh9" frameborder="0" allowFullScreen="true"></iframe>')
```

[Back to Portfolio](https://olamideadu.com)
